language: clojure
jdk:
  - oraclejdk8

node_js: "8"
install: npm --version && npm install -g npm@6 && npm install

script:
  - lein do clean, compile, check, simple-release
  - npx expo-cli login -u ${EXP_USERNAME} -p ${EXP_PASSWORD} --non-interactive
  - npx expo-cli publish --release-channel ${TRAVIS_PULL_REQUEST_BRANCH}

notifications:
  email:
    on_success: always
